Repository NatLibFi/Skosmos, pull requests merged in 2019-01, with the labels that each got.

#834 Add some phpdocs & type hinting
  controller/WebController.php
  model/ConceptProperty.php
  model/Request.php
  model/Vocabulary.php
  model/sparql/GenericSparql.php
Labels: enhancement, php7

#837 Don't perform label and subPropertyOf lookups for well-known properties
  model/Concept.php
Labels: bug, performance

#841 Remove duplicated array index
  controller/RestController.php
Labels: bug
