Repository NatLibFi/Skosmos, pull requests merged in 2019-02, with the labels that each got.

#848 Changed SPARQL query in Count Lang Concepts
  model/sparql/GenericSparql.php
Labels: performance

#849 Avoid unnecessary properties when calling getMappingProperties from search result page
  model/Concept.php
  view/search-result.twig
Labels: enhancement, performance, search results

#847 Avoid second unnecessary getProperties call in search result list
  view/search-result.twig
Labels: bug, needs backport, performance

#850 Add a cache to avoid computing language order many times during a request
  model/VocabularyConfig.php
Labels: enhancement, performance
