Repository NatLibFi/Skosmos, pull requests merged in 2020-04, with the labels that each got.

#968 Fix static analysis issues
  .jshintrc
  controller/Controller.php
  controller/WebController.php
  model/Model.php
  model/VocabularyConfig.php
  resource/css/styles.css
  resource/js/docready.js
  resource/js/groups.js
  resource/js/hierarchy.js
  resource/js/scripts.js
Labels: enhancement

#969 Shorten long lists of property values, with link to expand
  resource/css/styles.css
  resource/js/docready.js
  resource/js/scripts.js
  resource/translations/en/LC_MESSAGES/skosmos.mo
  resource/translations/fi/LC_MESSAGES/skosmos.mo
  resource/translations/skosmos_en.po
  resource/translations/skosmos_fi.po
  resource/translations/skosmos_sv.po
  resource/translations/sv/LC_MESSAGES/skosmos.mo
  view/scripts.twig
Labels: enhancement

#972 Add Danish translation by Sebastian Esp Nielsen and A I
  resource/translations/da/LC_MESSAGES/skosmos.mo
  resource/translations/skosmos_da.po
Labels: enhancement, translations

#970 Issue874 parameterized plugin
  controller/WebController.php
  model/VocabularyConfig.php
  tests/VocabularyConfigTest.php
  tests/testconfig.ttl
  view/scripts.twig
Labels: enhancement

#973 Avoid displaying empty type field in search result list
  view/search-result.twig
Labels: bug
