Repository NatLibFi/Skosmos, pull requests merged in 2020-02, with the labels that each got.

#919 Upgrade to PHP 7.1-7.4 and Fuseki 3.14.0
  .travis.yml
  tests/init_fuseki.sh
Labels: enhancement

#923 Use phpdbg instead of Xdebug for Travis coverage
  .travis.yml
Labels: enhancement, tests

#921 Resolve Wikidata URIs via LDF endpoint and LC URIs using HEAD requests
  model/Concept.php
  model/ConceptMappingPropertyValue.php
  model/ConceptPropertyValue.php
  model/Model.php
  model/resolver/LOCResource.php
  model/resolver/LinkedDataResource.php
  model/resolver/RemoteResource.php
  model/resolver/Resolver.php
  model/resolver/WDQSResource.php
  tests/ResolverTest.php
Labels: enhancement, performance

#928 Add more information about Wikidata sitelinks to enable wiki widget
  model/resolver/WDQSResource.php
Labels: bug

#924 Fix issues reported by SonarCloud
  controller/Controller.php
  controller/Honeypot.php
  controller/RestController.php
  controller/WebController.php
  model/Concept.php
  model/ConceptMappingPropertyValue.php
  model/ConceptPropertyValue.php
  model/ConceptSearchParameters.php
  model/Model.php
  resource/js/docready.js
  tests/DataObjectTest.php
  tests/GlobalConfigTest.php
  tests/ModelTest.php
  tests/VocabularyCategoryTest.php
Labels: enhancement

#929 fix some test coverage annotations after PR #921
  tests/ModelTest.php
  tests/ResolverTest.php
Labels: bug, tests

#931 remove extra closing div tag and remove duplicate code; fixes breakin…
  view/concept-shared.twig
Labels: bug

#899 Fix "Any language" label not showing in edge case
  resource/js/docready.js
Labels: bug

#933 do not use relative IRIs in assembler file; upgrade to TDB2; rename /…
  tests/GenericSparqlTest.php
  tests/GlobalConfigTest.php
  tests/JenaTextSparqlTest.php
  tests/ModelTest.php
  tests/VocabularyTest.php
  tests/fuseki-assembler.ttl
  tests/init_fuseki.sh
  tests/jenatestconfig.ttl
  tests/testconfig-fordefaults.ttl
  tests/testconfig.ttl
Labels: size-small, tests

#939 Fix bad quotes in SMTP header.
  controller/WebController.php
Labels: bug
