Repository NatLibFi/Skosmos, pull requests merged in 2021-02, with the labels that each got.

#1104 add an isset test and default value for possibly undefined index
  controller/RestController.php
Labels: enhancement

#1102 add isset tests to fix undefined index PHP notices in RestController
  controller/RestController.php
Labels: bug

#1097 add treatment for JSON-LD vocabulary data dump; fixes #1096
  view/vocab-shared.twig
Labels: enhancement

#1103 fixes undefined offset by adding an isset test
  controller/WebController.php
  model/sparql/GenericSparql.php
  tests/GenericSparqlTest.php
  tests/JenaTextSparqlTest.php
Labels: enhancement, needs discussion

#1120 Disable Travis build job that uses Fuseki snapshot
  .travis.yml
Labels: bug, tests
