Repository NatLibFi/Skosmos, pull requests merged in 2021-11, with the labels that each got.

#1231 Avoid uncaught fatal errors in REST API if vocabulary ID not found
  rest.php
Labels: bug, REST

#1223 Move allcaps in property-labels (and vocabulary-category) from twig to css
  resource/css/styles.css
  view/concept-shared.twig
  view/vocab-shared.twig
  view/vocabularylist.twig
Labels: enhancement

#1227 Fix hierarchy js error for special characters in prefLabels
  resource/js/hierarchy.js
Labels: bug

#1234 Fix language switcher "eating" part of vocids that end in a langcode (e.g. "interessen" and "en")
  view/topbar.twig
Labels: bug

#1241 Remove float property of reified property element
  resource/css/styles.css
Labels: bug

#1239 Normalize the search term
  model/ConceptSearchParameters.php
Labels: bug

#1244 Custom labels and tooltips for properties in concept view
  controller/WebController.php
  model/VocabularyConfig.php
  tests/VocabularyConfigTest.php
  tests/testconfig.ttl
  view/concept-shared.twig
Labels: enhancement

#1226 Themeing Enhancement: Extract and consolidate colors, create css variables
  resource/css/styles.css
Labels: enhancement

#1235 Faster docker build.
  dockerfiles/Dockerfile.ubuntu
Labels: enhancement
