Repository NatLibFi/Skosmos, pull requests merged in 2021-09, with the labels that each got.

#1196 Fix sidebar navigation after erroneous page
  controller/WebController.php
  model/Vocabulary.php
  resource/css/styles.css
  resource/js/docready.js
  view/error-page.twig
Labels: bug

#1195 Improve search error handling
  controller/WebController.php
  model/Vocabulary.php
  resource/css/styles.css
  resource/translations/en/LC_MESSAGES/skosmos.mo
  resource/translations/fi/LC_MESSAGES/skosmos.mo
  resource/translations/skosmos_en.po
  resource/translations/skosmos_fi.po
  resource/translations/skosmos_sv.po
  resource/translations/sv/LC_MESSAGES/skosmos.mo
  view/search-result.twig
  view/vocab-search-listing.twig
Labels: bug

#1194 error-resistant Vocabulary->getInfo()
  resource/translations/en/LC_MESSAGES/skosmos.mo
  resource/translations/fi/LC_MESSAGES/skosmos.mo
  resource/translations/skosmos_en.po
  resource/translations/skosmos_fi.po
  resource/translations/skosmos_sv.po
  resource/translations/sv/LC_MESSAGES/skosmos.mo
  view/vocab-shared.twig
Labels: bug

#1200 Add dependency on symfony/polyfill-php80 to define ValueError
  composer.json
Labels: bug

#1199 Cleanup translation files and rename trans_script to compile-translations
  resource/translations/compile-translations
  resource/translations/skosmos_ar.po
  resource/translations/skosmos_de.mo
  resource/translations/skosmos_en.mo
  resource/translations/skosmos_fi.mo
  resource/translations/skosmos_nb.mo
  resource/translations/skosmos_sv.mo
Labels: enhancement, translations

#1197 Fixes for searches, ajax, waypoints, easyrdf HTTP client errors
  controller/WebController.php
  model/DataObject.php
  model/Model.php
  resource/css/styles.css
  resource/js/docready.js
  resource/js/scripts.js
  resource/translations/en/LC_MESSAGES/skosmos.mo
  resource/translations/fi/LC_MESSAGES/skosmos.mo
  resource/translations/skosmos_en.po
  resource/translations/skosmos_fi.po
  resource/translations/skosmos_sv.po
  resource/translations/sv/LC_MESSAGES/skosmos.mo
  view/scripts.twig
  view/search-result.twig
  view/vocab-search-listing.twig
Labels: bug

#1207 Replace NBSP by spaces
  model/DataObject.php
  model/Model.php
  model/Vocabulary.php
  resource/js/scripts.js
Labels: bug

#1205 Add "lexical" and "natural" sort strategies for notation codes
  model/Concept.php
  model/ConceptProperty.php
  model/ConceptPropertyValue.php
  model/VocabularyConfig.php
  resource/js/hierarchy.js
  resource/js/scripts.js
  tests/ConceptPropertyTest.php
  tests/ConceptPropertyValueTest.php
  tests/VocabularyConfigTest.php
  tests/test-vocab-data/test-notation-sort.ttl
  tests/testconfig.ttl
  view/scripts.twig
Labels: enhancement

#1211 Allow clicking on either label or notation in hierarchy
  resource/js/docready.js
Labels: bug

#1212 Fix notation data type tests
  model/ConceptPropertyValueLiteral.php
  tests/ConceptPropertyValueLiteralTest.php
Labels: bug, tests, classification
