Repository NatLibFi/Skosmos, pull requests merged in 2022-05, with the labels that each got.

#1319 use Font Awesome fonts for icons
  resource/css/styles.css
  resource/fontawesome/css/fontawesome.css
  resource/fontawesome/css/regular.css
  resource/fontawesome/css/solid.css
  resource/fontawesome/webfonts/fa-regular-400.ttf
  resource/fontawesome/webfonts/fa-regular-400.woff2
  resource/fontawesome/webfonts/fa-solid-900.ttf
  resource/fontawesome/webfonts/fa-solid-900.woff2
  resource/pics/clipboard.svg
  view/concept-shared.twig
  view/light.twig
Labels: enhancement

#1317 Fix SKOS-XL tooltips
  model/ConceptPropertyValueLiteral.php
  resource/translations/en/LC_MESSAGES/skosmos.mo
  resource/translations/fi/LC_MESSAGES/skosmos.mo
  resource/translations/skosmos_en.po
  resource/translations/skosmos_fi.po
  resource/translations/skosmos_sv.po
  resource/translations/sv/LC_MESSAGES/skosmos.mo
  tests/ConceptPropertyValueLiteralTest.php
  view/concept-shared.twig
Labels: bug

#1318 Create SECURITY.md
  SECURITY.md
Labels: needs discussion, maintenance

#1321 minor CSS tweaks after Bootstrap 5 update
  resource/css/styles.css
Labels: bug
