Repository NatLibFi/Skosmos, pull requests merged in 2022-06, with the labels that each got.

#1322 Modify checklist in PR template
  PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#1330 Avoid introducing extra whitespace around literal values on the concept page
  view/concept-shared.twig
Labels: bug

#1331 Update translations from Transifex
  resource/translations/ar/LC_MESSAGES/skosmos.mo
  resource/translations/da/LC_MESSAGES/skosmos.mo
  resource/translations/de/LC_MESSAGES/skosmos.mo
  resource/translations/es/LC_MESSAGES/skosmos.mo
  resource/translations/fa/LC_MESSAGES/skosmos.mo
  resource/translations/fr/LC_MESSAGES/skosmos.mo
  resource/translations/fy/LC_MESSAGES/skosmos.mo
  resource/translations/it/LC_MESSAGES/skosmos.mo
  resource/translations/nb/LC_MESSAGES/skosmos.mo
  resource/translations/nl/LC_MESSAGES/skosmos.mo
  resource/translations/nn/LC_MESSAGES/skosmos.mo
  resource/translations/pl/LC_MESSAGES/skosmos.mo
  resource/translations/pt/LC_MESSAGES/skosmos.mo
  resource/translations/pt_BR/LC_MESSAGES/skosmos.mo
  resource/translations/ru/LC_MESSAGES/skosmos.mo
  resource/translations/skosmos_ar.po
  resource/translations/skosmos_da.po
  resource/translations/skosmos_de.po
  resource/translations/skosmos_es.po
  resource/translations/skosmos_fa.po
  resource/translations/skosmos_fr.po
  resource/translations/skosmos_fy.po
  resource/translations/skosmos_it.po
  resource/translations/skosmos_lv.po
  resource/translations/skosmos_nb.po
  resource/translations/skosmos_nl.po
  resource/translations/skosmos_nn.po
  resource/translations/skosmos_pl.po
  resource/translations/skosmos_pt.po
  resource/translations/skosmos_pt_BR.po
  resource/translations/skosmos_ru.po
  resource/translations/skosmos_zh.po
  resource/translations/zh/LC_MESSAGES/skosmos.mo
Labels: enhancement

#1332 API docs: Add 'uri' parameter to groupMembers
  swagger.json
Labels: bug, REST
