Repository NatLibFi/Skosmos, pull requests merged in 2022-02, with the labels that each got.

#1266 Support PHP 8.0
  .github/workflows/ci.yml
  composer.json
  model/Vocabulary.php
  model/sparql/GenericSparql.php
  phpunit.xml
  tests/bootstrap.php
Labels: enhancement

#1273 Upgrade to newest Fuseki 4.4.0 for running unit tests
  tests/init_fuseki.sh
Labels: enhancement

#1262 Allow plugin robloach/component-installer, because it is required by components/handlebars.js
  .gitignore
  composer.json
  composer.lock
Labels: enhancement

#1277 Enable GitHub Actions CI runs for pull requests (from forks)
  .github/workflows/ci.yml
Labels: enhancement, tests

#1276 Do not treat 0 as boolean value in the REST controller
  model/ConceptSearchParameters.php
  tests/ConceptSearchParametersTest.php
Labels: bug
