Repository NatLibFi/Skosmos, pull requests merged in 2022-03, with the labels that each got.

#1251 Redirect error log to stderr for docker logs.
  dockerfiles/Dockerfile.ubuntu
Labels: enhancement

#1282 Reformat remaining JSON strings in RestControllerTest to avoid long lines
  tests/RestControllerTest.php
Labels: enhancement, tests

#1283 Avoid unnecessary encoding of slashes in URIs in RestControllerTest
  tests/RestControllerTest.php
Labels: enhancement, tests

#1284 Only shorten URIs of types in the SKOS namespace in the search results
  model/sparql/GenericSparql.php
  tests/RestControllerTest.php
Labels: bug

#1290 Permit GitHub Actions CI to write Packages, needed for php-build caching
  .github/workflows/ci.yml
Labels: bug, tests

#1293 drop useless SKOSMOS_VERSION build arg from Dockerfile
  dockerfiles/Dockerfile.ubuntu
Labels: bug
