Repository NatLibFi/Skosmos, pull requests merged in 2022-09, with the labels that each got.

#1353 Add Northern Sámi (se) UI translation
  resource/translations/se/LC_MESSAGES/skosmos.mo
  resource/translations/skosmos_se.po
Labels: enhancement, translations

#1358 Add failure message explaining how to fix Composer/git version mismatch
  tests/ModelTest.php
Labels: enhancement, tests

#1357 Use the --font-size variable for versal, and set width: auto for the restore-breadcrumbs link
  resource/css/styles.css
  resource/js/scripts.js
Labels: bug

#1356 Graceful handling of partial SKOS XL data for concept labels
  model/Concept.php
  model/ConceptPropertyValueLiteral.php
  model/LabelSkosXL.php
  tests/ConceptPropertyValueLiteralTest.php
  tests/ConceptTest.php
  view/concept-shared.twig
Labels: bug

#1354 Fix header bar search form
  resource/js/docready.js
  resource/js/scripts.js
  view/headerbar.twig
Labels: bug

#1362 fix display of DC properties in reified property value tooltips
  model/ConceptPropertyValue.php
  tests/ConceptPropertyValueTest.php
  tests/test-vocab-data/xl.ttl
Labels: bug

#1365 Remove jQuery UI dependency
  composer.json
  view/light.twig
  view/scripts.twig
Labels: enhancement

#1324 Replace qtip JS library by a pure CSS tooltip
  composer.json
  resource/css/jquery.qtip.min.css
  resource/css/styles.css
  resource/js/docready.js
  view/changes.twig
  view/concept-shared.twig
  view/group-contents.twig
  view/group-index.twig
  view/light.twig
  view/scripts.twig
  view/search-result.twig
  view/topbar.twig
  view/vocab.twig
Labels: enhancement

#1352 Upgrade to jQuery 3.6
  composer.json
  resource/css/jquery.mCustomScrollbar.css
  resource/css/styles.css
  resource/js/docready.js
  resource/js/hierarchy.js
  view/light.twig
  view/scripts.twig
Labels: enhancement
