Repository NatLibFi/Skosmos, pull requests merged in 2022-04, with the labels that each got.

#1300 drop unused URI.js dependency
  composer.json
  view/scripts.twig
Labels: bug

#1305 Updated Handlebars v4.7.6 -> v4.7.7
  composer.json
Labels: maintenance

#1304 Fix font color and size after Bootstrap 5 upgrade
  resource/css/styles.css
Labels: bug

#1307 Sanitize language switching URLs
  model/Request.php
  tests/RequestTest.php
Labels: bug

#1308 Store current Skosmos version in composer.json
  .github/workflows/ci.yml
  composer.json
  model/Model.php
  tests/ModelTest.php
Labels: enhancement

#1309 Use copy to clipboard icon from Font Awesome Free set
  resource/css/styles.css
  resource/pics/clipboard.svg
Labels: enhancement

#1310 fix font size of autocomplete entries after Bootstrap 5 upgrade
  resource/css/styles.css
Labels: bug

#1313 add Latvian translation
  resource/translations/lv/LC_MESSAGES/skosmos.mo
  resource/translations/skosmos_lv.po
Labels: enhancement, translations

#1312 Upgrade to PHPUnit 9, drop PHP 7.2 support
  .github/workflows/ci.yml
  composer.json
  phpunit.xml
  tests/ConceptTest.php
  tests/VocabularyConfigTest.php
Labels: enhancement

#1315 fix 'Any language' choice in language selection menu
  resource/js/docready.js
  view/headerbar.twig
Labels: bug

#1187 provide translations for skosmos:marcSourceCode
  resource/translations/en/LC_MESSAGES/skosmos.mo
  resource/translations/fi/LC_MESSAGES/skosmos.mo
  resource/translations/skosmos_en.po
  resource/translations/skosmos_fi.po
  resource/translations/skosmos_sv.po
  resource/translations/sv/LC_MESSAGES/skosmos.mo
Labels: bug

#1314 Fix sidebar search, post bootstrap
  resource/css/styles.css
  resource/js/docready.js
  view/light.twig
Labels: bug
