Repository NatLibFi/Skosmos, pull requests merged in 2023-05, with the labels that each got.

#1442 Add Cypress e2e tests
  .gitignore
  cypress.config.js
  cypress/e2e/spec.cy.js
  cypress/support/commands.js
  cypress/support/e2e.js
  package.json
Labels: enhancement, tests

#1456 expand Cypress tests to cover all current page types + set baseUrl
  cypress.config.js
  cypress/e2e/about.cy.js
  cypress/e2e/concept.cy.js
  cypress/e2e/feedback.cy.js
  cypress/e2e/global-search.cy.js
  cypress/e2e/landing.cy.js
  cypress/e2e/vocab-home.cy.js
  cypress/e2e/vocab-search.cy.js
Labels: enhancement, tests

#1457 Fixes and unit tests for UI language detection
  composer.json
  controller/WebController.php
  dockerfiles/config/config-docker-compose.ttl
  dockerfiles/config/config-docker.ttl
  index.php
  model/Request.php
  tests/GlobalConfigTest.php
  tests/WebControllerTest.php
  tests/testconfig.ttl
Labels: bug

#1455 UI language negotiation fix
  controller/WebController.php
  dockerfiles/config/config-docker-compose.ttl
  dockerfiles/config/config-docker.ttl
Labels: bug

#1458 Language negotiation fixes for Skosmos 3
  composer.json
  dockerfiles/config/config-docker-compose.ttl
  dockerfiles/config/config-docker.ttl
  src/controller/WebController.php
  src/index.php
  src/model/Request.php
  tests/GlobalConfigTest.php
  tests/WebControllerTest.php
  tests/testconfig.ttl
Labels: bug

#1464 Partial page load for concepts in alphabetical index
  resource/js/tab-alpha.js
  src/view/scripts.inc
Labels: enhancement, front-end

#1460 About.twig updated
  cypress/e2e/about.cy.js
  src/view/about-info.inc
  src/view/about.twig
Labels: enhancement
