Repository NatLibFi/Skosmos, pull requests merged in 2023-09, with the labels that each got.

#1509 Use dockerized Skosmos for Cypress tests
  .github/workflows/ci.yml
  cypress.config.js
  tests/GlobalConfigTest.php
  tests/RestControllerTest.php
  tests/cypress/template/error.cy.js
  tests/docker-compose.yml
  tests/init_containers.sh
  tests/testconfig-basehref.ttl
  tests/testconfig.ttl
Labels: enhancement, tests

#1517 fix: set correct SKOSMOS_SPARQL_ENDPOINT for Skosmos container
  dockerfiles/docker-compose.yml
  tests/docker-compose.yml
Labels: bug

#1518 Run Cypress under GitHub Actions & install Node dependencies in Docker image
  .dockerignore
  .github/workflows/ci.yml
  dockerfiles/Dockerfile.ubuntu
Labels: enhancement

#1529 Show deprecated concepts without replacement in change list
  model/sparql/GenericSparql.php
  tests/GenericSparqlTest.php
  tests/RestControllerTest.php
  tests/VocabularyTest.php
  tests/WebControllerTest.php
  tests/test-vocab-data/changes.ttl
  view/changes.twig
Labels: bug

#1531 Added a test vocabulary cut from YSO (Archaeology Group) and its conf…
  tests/docs/README-little-yso.md
  tests/docs/generate-little-yso.rq
  tests/test-vocab-data/little-yso.ttl
  tests/testconfig.ttl
Labels: front-end

#1524 Issue 1521 hierarchy tab vue component
  resource/js/get-concept-url.js
  resource/js/partial-page-load.js
  resource/js/tab-alpha.js
  resource/js/tab-hierarchy.js
  src/controller/RestController.php
  src/view/scripts.inc
Labels: enhancement
