Repository NatLibFi/Skosmos, pull requests merged in 2023-08, with the labels that each got.

#1425 Fix for #1389 checking that skosxl properties are only shown for correct language
  model/ConceptPropertyValueLiteral.php
  model/LabelSkosXL.php
  tests/ConceptPropertyValueLiteralTest.php
  tests/test-vocab-data/xl.ttl
Labels: bug

#1477 Use Apache Jena Fuseki docker image
  dockerfiles/README.md
  dockerfiles/config/skosmos.ttl
  dockerfiles/docker-compose.yml
  dockerfiles/jena-fuseki2-docker/Dockerfile
  dockerfiles/jena-fuseki2-docker/README.md
  dockerfiles/jena-fuseki2-docker/download.sh
  dockerfiles/jena-fuseki2-docker/entrypoint.sh
  dockerfiles/jena-fuseki2-docker/log4j2.properties
Labels: maintenance

#1495 Skosmos 3: Use Apache Jena Fuseki docker image
  dockerfiles/README.md
  dockerfiles/config/skosmos.ttl
  dockerfiles/docker-compose.yml
  dockerfiles/jena-fuseki2-docker/Dockerfile
  dockerfiles/jena-fuseki2-docker/README.md
  dockerfiles/jena-fuseki2-docker/download.sh
  dockerfiles/jena-fuseki2-docker/entrypoint.sh
  dockerfiles/jena-fuseki2-docker/log4j2.properties
Labels: enhancement

#1501 Issue1497 unified cypress folders with other test folders
  cypress.config.js
  package.json
  tests/cypress.config.js
  tests/cypress/accessibility/axe-about.cy.js
  tests/cypress/accessibility/axe-concept.cy.js
  tests/cypress/accessibility/axe-feedback.cy.js
  tests/cypress/accessibility/axe-global-search.cy.js
  tests/cypress/accessibility/axe-landing.cy.js
  tests/cypress/accessibility/axe-vocab-home.cy.js
  tests/cypress/accessibility/axe-vocab-search.cy.js
  tests/cypress/accessibility/axe-vocab.cy.js
  tests/cypress/e2e/README.md
  tests/cypress/fixtures/example.json
  tests/cypress/support/accessibility.js
  tests/cypress/support/commands.js
  tests/cypress/support/e2e.js
  tests/cypress/support/index.js
  tests/cypress/template/about.cy.js
  tests/cypress/template/concept.cy.js
  tests/cypress/template/error.cy.js
  tests/cypress/template/feedback.cy.js
  tests/cypress/template/global-search.cy.js
  tests/cypress/template/landing.cy.js
  tests/cypress/template/vocab-home.cy.js
  tests/cypress/template/vocab-search.cy.js
Labels: enhancement

#1507 fix implementation of ConceptPropertyValue.getLang + add test
  src/model/ConceptPropertyValue.php
  tests/ConceptPropertyValueTest.php
Labels: bug

#1498 Skosmos 3 docker: upgrade to Ubuntu 22.04 base image and PHP 8.1
  dockerfiles/Dockerfile.ubuntu
Labels: maintenance
