Repository NatLibFi/Skosmos, pull requests merged in 2023-11, with the labels that each got.

#1380 Autocomplete to support distinguisher labels in case of shared preferred labels
  model/VocabularyConfig.php
  model/sparql/GenericSparql.php
  resource/css/styles.css
  resource/js/docready.js
  swagger.json
  tests/GenericSparqlTest.php
  tests/VocabularyConfigTest.php
  tests/test-vocab-data/duplabel.ttl
  tests/testconfig.ttl
Labels: enhancement

#1534 Show deprecated concepts without replacement in change list (skosmos 3)
  src/model/sparql/GenericSparql.php
  tests/GenericSparqlTest.php
  tests/RestControllerTest.php
  tests/VocabularyTest.php
  tests/WebControllerTest.php
  tests/test-vocab-data/changes.ttl
Labels: bug

#1545 Top-level docker-compose.yml for Skosmos 3
  docker-compose.yml
  dockerfiles/README.md
  tests/docker-compose.yml
Labels: enhancement

#1546 PHP 8.2 support for Skosmos 3 (avoid dynamic properties)
  .github/workflows/ci.yml
  src/model/ConceptProperty.php
  src/model/PluginRegister.php
  src/model/VocabularyConfig.php
  tests/ConceptSearchParametersTest.php
  tests/ConceptTest.php
  tests/FeedbackTest.php
  tests/GenericSparqlTest.php
  tests/JenaTextSparqlTest.php
  tests/PluginRegisterTest.php
  tests/VocabularyTest.php
Labels: enhancement

#1550 Rename little-yso test vocabulary to simply YSO and reconfigure it
  tests/ModelTest.php
  tests/test-vocab-data/yso.ttl
  tests/testconfig.ttl
Labels: enhancement, tests

#1553 Harden JSONP callback filter
  controller/RestController.php
Labels: bug

#1554 Harden JSONP callback filter (Skosmos 3)
  src/controller/RestController.php
Labels: bug

#1549 Concept page template and Cypress tests
  resource/css/skosmos.css
  src/controller/RestController.php
  src/controller/WebController.php
  src/model/Vocabulary.php
  src/view/about.twig
  src/view/concept-card.inc
  src/view/concept.twig
  src/view/feedback.twig
  src/view/scripts.inc
  src/view/vocab-info.inc
  tests/ConceptMappingPropertyValueTest.php
  tests/ConceptPropertyTest.php
  tests/ConceptPropertyValueLiteralTest.php
  tests/ConceptPropertyValueTest.php
  tests/ConceptTest.php
  tests/Http304Test.php
  tests/VocabularyTest.php
  tests/cypress/template/concept.cy.js
  tests/cypress/template/vocab-home.cy.js
Labels: enhancement

#1556 Add styling to sidebar
  resource/css/skosmos.css
  resource/js/tab-alpha.js
  resource/js/tab-hierarchy.js
  src/view/sidebar.inc
  tests/cypress/template/vocab-home.cy.js
Labels: enhancement

#1552 Better template and styling for the concept mappings component
  resource/css/skosmos.css
  resource/js/concept-mappings.js
  src/view/concept-card.inc
  tests/cypress/template/concept.cy.js
Labels: enhancement

#1559 fix guessVocabularyFromURI when some vocabulary has no URI space
  model/Model.php
Labels: bug

#1560 fix guessVocabularyFromURI when some vocabulary has no URI space (Skosmos 3)
  src/model/Model.php
Labels: bug

#1555 Add E2E test: navigate from front page to vocabulary search and concept page
  tests/cypress/e2e/fp-lang-yso-clang-result-vocab.cy.js
Labels: enhancement, tests

#1562 Add logos for Skosmos 3
  resource/css/skosmos.css
  resource/pics/skosmos-NEGA-RGB.svg
  resource/pics/skosmos-RGB.svg
  src/view/base-template.twig
Labels: enhancement
