Repository NatLibFi/Skosmos, pull requests merged in 2023-03, with the labels that each got.

#1423 fix conversion of DateTime to string in getContainsHtml
  model/ConceptPropertyValueLiteral.php
  tests/ConceptPropertyValueLiteralTest.php
Labels: bug

#1419 Enhance the feature request template with additional instructions
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#1409 Don't crash on incomplete vocabulary configuration
  model/Vocabulary.php
  view/scripts.twig
Labels: bug

#1424 update German & Northern Sámi translations + English language template
  resource/translations/de/LC_MESSAGES/skosmos.mo
  resource/translations/en/LC_MESSAGES/skosmos.mo
  resource/translations/se/LC_MESSAGES/skosmos.mo
  resource/translations/skosmos_de.po
  resource/translations/skosmos_en.po
  resource/translations/skosmos_se.po
Labels: enhancement, translations
