Repository NatLibFi/Skosmos, pull requests merged in 2024-08, with the labels that each got.

#1636 Add loading spinners to Vue components
  resource/js/concept-mappings.js
  resource/js/tab-hierarchy.js
  resource/js/term-counts.js
  resource/js/vocab-counts.js
  tests/cypress/template/concept.cy.js
  tests/cypress/template/vocab-home.cy.js
Labels: enhancement

#1638 Hierarchical view style fixes
  resource/css/skosmos.css
  resource/js/tab-hierarchy.js
  resource/pics/black-lower-right-triangle.png
  resource/pics/lower-right-triangle.png
Labels: enhancement

#1637 Add notation codes to sidebar
  resource/css/skosmos.css
  resource/js/tab-alpha.js
  resource/js/tab-hierarchy.js
  tests/cypress/template/concept.cy.js
  tests/cypress/template/vocab-home.cy.js
Labels: enhancement

#1625 SEO: improved titles for Skosmos 3 generated HTML pages
  resource/translations/skosmos_en.po
  resource/translations/skosmos_fi.po
  resource/translations/skosmos_se.po
  resource/translations/skosmos_sv.po
  src/controller/WebController.php
  src/view/about.twig
  src/view/base-template.twig
  src/view/concept.twig
  src/view/error.twig
  src/view/feedback.twig
  src/view/vocab-home.twig
  src/view/vocab-search.twig
  tests/cypress/template/about.cy.js
  tests/cypress/template/concept.cy.js
  tests/cypress/template/error.cy.js
  tests/cypress/template/feedback.cy.js
  tests/cypress/template/landing.cy.js
  tests/cypress/template/vocab-home.cy.js
  tests/cypress/template/vocab-search.cy.js
Labels: enhancement

#1639 Fix sidebar width on window resize
  resource/css/skosmos.css
  resource/js/tab-alpha.js
  resource/js/tab-hierarchy.js
Labels: enhancement

#1646 use PUT for initialising Fuseki to ensure existing vocabularies are overwritten before running tests
  tests/init_containers.sh
Labels: bug, tests

#1644 SEO: long title on landing page (skosmos:serviceNameLong configuration setting)
  src/model/BaseConfig.php
  src/model/GlobalConfig.php
  src/view/base-template.twig
  src/view/landing.twig
  tests/GlobalConfigTest.php
  tests/cypress/template/about.cy.js
  tests/cypress/template/concept.cy.js
  tests/cypress/template/error.cy.js
  tests/cypress/template/feedback.cy.js
  tests/cypress/template/landing.cy.js
  tests/cypress/template/vocab-home.cy.js
  tests/cypress/template/vocab-search.cy.js
  tests/testconfig.ttl
Labels: enhancement

#1645 Fix sidebar Vue component sizing
  resource/js/tab-alpha.js
  resource/js/tab-hierarchy.js
Labels: bug

#1647 SEO: descriptions on landing, about and feedback pages
  src/model/GlobalConfig.php
  src/view/about.twig
  src/view/base-template.twig
  src/view/feedback.twig
  src/view/landing.twig
  tests/GlobalConfigTest.php
  tests/cypress/template/about.cy.js
  tests/cypress/template/feedback.cy.js
  tests/cypress/template/landing.cy.js
  tests/testconfig.ttl
Labels: enhancement

#1649 Use setup-php instead of php-actions so that all CI steps are run using the same PHP version
  .github/workflows/ci.yml
Labels: bug, tests

#1651 Order hierarchy by notation
  resource/js/tab-hierarchy.js
  tests/cypress/template/sidebar.cy.js
Labels: enhancement

#1652 Increase HTTP timeout in test configuration to fix flaky Cypress mapping tests
  tests/GlobalConfigTest.php
  tests/testconfig.ttl
Labels: bug, tests

#1650 Bootstrap search bar
  resource/css/skosmos.css
  resource/js/vocab-search.js
  tests/cypress/e2e/fp-lang-yso-clang-result-vocab.cy.js
  tests/cypress/template/vocab-search-bar.cy.js
Labels: enhancement

#1654 Add notation codes to concept page
  resource/css/skosmos.css
  src/view/concept-card.inc
  tests/cypress/template/concept.cy.js
Labels: enhancement

#1655 Refactor: Convert linkUrlFilter to a Twig extension class
  src/controller/Controller.php
  src/controller/LinkUrlExtension.php
  src/controller/RestController.php
  src/controller/WebController.php
Labels: enhancement

#1657 SEO: vocab description, site name, type, canonical URL
  src/model/Request.php
  src/model/VocabularyConfig.php
  src/view/about.twig
  src/view/base-template.twig
  src/view/concept.twig
  src/view/error.twig
  src/view/feedback.twig
  src/view/landing.twig
  src/view/vocab-home.twig
  src/view/vocab-search.twig
  tests/RequestTest.php
  tests/VocabularyConfigTest.php
  tests/VocabularyTest.php
  tests/cypress/template/about.cy.js
  tests/cypress/template/concept.cy.js
  tests/cypress/template/error.cy.js
  tests/cypress/template/feedback.cy.js
  tests/cypress/template/landing.cy.js
  tests/cypress/template/vocab-home.cy.js
  tests/cypress/template/vocab-search.cy.js
  tests/testconfig.ttl
Labels: enhancement

#1659 SEO: add description metadata to concept page
  resource/translations/skosmos_en.po
  resource/translations/skosmos_fi.po
  resource/translations/skosmos_se.po
  resource/translations/skosmos_sv.po
  src/view/concept.twig
  tests/cypress/template/concept.cy.js
Labels: enhancement

#1664 Fix flaky getResourceFromUri test by increasing httpTimeout (Skosmos 2)
  tests/GlobalConfigTest.php
  tests/testconfig.ttl
Labels: bug, tests, Skosmos 2.X

#1663 Update Latvian (lv) translation by @CaptSolo from Transifex
  resource/translations/lv/LC_MESSAGES/skosmos.mo
  resource/translations/skosmos_lv.po
Labels: enhancement, translations, Skosmos 2.X

#1661 Css fixes for the footer bar
  resource/css/skosmos.css
  src/view/base-template.twig
Labels: front-end

#1667 Css fixes for background for different page types
  src/view/base-template.twig
Labels: front-end

#1658 Override default property labels on concept page
  resource/js/concept-mappings.js
  src/view/concept-card.inc
  src/view/scripts.inc
  tests/VocabularyConfigTest.php
  tests/cypress/template/concept.cy.js
  tests/test-vocab-data/conceptPropertyLabels.ttl
  tests/testconfig.ttl
Labels: enhancement

#1668 Css fixes for the header bar
  resource/css/skosmos.css
  src/view/base-template.twig
Labels: front-end

#1671 Upgrade EasyRdf to fix Turtle fragment URIs
  .github/workflows/ci.yml
  README.md
  composer.json
Labels: bug, Skosmos 2.X

#1672 Fix Skosmos 2 twig syntax error on search result page
  view/vocab-search-listing.twig
Labels: bug, Skosmos 2.X

#1674 Fix deprecated concept pages (Skosmos 3)
  src/model/Concept.php
  tests/ConceptTest.php
  tests/test-vocab-data/default_graph.ttl
Labels: bug

#1675 Upgrade to sweetrdf/easyrdf 1.13.* to fix Turtle fragment URIs
  composer.json
Labels: bug
