Repository NatLibFi/Skosmos, pull requests merged in 2024-12, with the labels that each got.

#1706 Don't HTML encode quotes in REST API callback, to fix ONKI Selector (Skosmos 3)
  src/controller/RestController.php
Labels: bug, REST

#1715 Issue1709 frontend dependencies
  package.json
Labels: maintenance, front-end

#1717 Set the UI language cookie
  resource/js/navbar.js
  src/view/base-template.twig
  src/view/scripts.inc.twig
  tests/cypress/template/navbar-languages.cy.js
Labels: enhancement

#1711 Set HTTP user-agent to 'Skosmos' when performing requests
  src/model/resolver/LinkedDataResource.php
  src/model/resolver/WDQSResource.php
  src/model/sparql/GenericSparql.php
Labels: enhancement

#1716 Extract Translation Keys from JavaScript Files (#1713)
  composer.json
  config/services.yaml
  src/util/JsTranslationExtractor.php
Labels: needs discussion

#1718 SKOS XL popup on concept page
  resource/css/skosmos.css
  src/view/concept-card.inc.twig
  src/view/xl-label.inc.twig
  tests/cypress/template/concept-full-vs-partial.cy.js
  tests/cypress/template/concept.cy.js
Labels: enhancement

#1719 Implement basic functionality of groups view using Vue
  resource/css/skosmos.css
  resource/js/tab-groups.js
  src/controller/WebController.php
  src/view/scripts.inc.twig
Labels: enhancement

#1725 Upgrade to PHPUnit 10
  composer.json
  phpunit.xml
  src/model/resolver/LOCResource.php
  tests/ConceptPropertyValueLiteralTest.php
  tests/ConceptTest.php
  tests/ResolverTest.php
  tests/RestControllerTest.php
  tests/VocabularyConfigTest.php
  tests/WebControllerTest.php
  tests/bootstrap.php
Labels: tests, maintenance

#1729 Implement groups view layout and styling
  resource/css/skosmos.css
  resource/js/tab-alpha.js
  resource/js/tab-groups.js
  resource/js/tab-hierarchy.js
Labels: enhancement

#1733 Add tests for groups component
  tests/cypress/template/sidebar-groups.cy.js
  tests/testconfig.ttl
Labels: tests

#1726 Issue1724 autocomplete result list
  resource/css/skosmos.css
  resource/js/vocab-search.js
  tests/cypress/template/vocab-search-bar.cy.js
Labels: front-end
