Repository NatLibFi/Skosmos, pull requests merged in 2024-03, with the labels that each got.

#1599 fix problem introduced by docker compose 2.24.6
  docker-compose.yml
Labels: bug

#1600 Scheduled Actions CI run every Monday morning
  .github/workflows/ci.yml
Labels: enhancement, tests

#1601 Order mappings on concept page first by source vocabulary, then by label
  src/model/ConceptMappingPropertyValue.php
  src/model/ConceptProperty.php
  src/model/ConceptPropertyValue.php
  src/model/ConceptPropertyValueLiteral.php
  tests/ConceptMappingPropertyValueTest.php
  tests/ConceptPropertyValueLiteralTest.php
  tests/ConceptPropertyValueTest.php
  tests/cypress/template/concept.cy.js
Labels: enhancement

#1604 Updated Cypress to the latest version 13.6.6
  package.json
Labels: maintenance

#1603 Fix height of sidebar
  resource/css/skosmos.css
  resource/js/tab-alpha.js
  resource/js/tab-hierarchy.js
  src/view/sidebar.inc
  tests/cypress/template/vocab-home.cy.js
Labels: enhancement

#1607 Enhanced Axe configuration to ensure compliance with WCAG 2.1 AA requirements (Issue1606)
  tests/cypress/support/accessibility.js
Labels: enhancement

#1602 Axe tests for the feedback page (Issue #1582)
  tests/cypress/accessibility/axe-feedback.cy.js
Labels: enhancement

#1608 Axe tests for the landing page (Issue #1582)
  tests/cypress/accessibility/axe-landing.cy.js
Labels: enhancement

#1605 Add Cypress tests for partial page load
  resource/js/concept-mappings.js
  resource/js/get-concept-url.js
  resource/js/partial-page-load.js
  resource/js/tab-alpha.js
  resource/js/tab-hierarchy.js
  resource/js/term-counts.js
  resource/js/vocab-counts.js
  resource/js/vocab-search.js
  src/view/scripts.inc
  tests/cypress/template/concept.cy.js
  tests/cypress/template/vocab-home.cy.js
  tests/test-vocab-data/test.ttl
Labels: enhancement, tests

#1610 Add automatic scrolling to hierarchy view
  resource/js/tab-hierarchy.js
Labels: enhancement

#1612 Reverts back to the original implicit usage of WCAG rules and changes the parameterization of CLI and GUI functions to their original state (#1611)
  tests/cypress/support/accessibility.js
Labels: bug, enhancement

#1609 implement fetchWithAbort and use it for partial page load, mappings & alphabetical index
  resource/js/concept-mappings.js
  resource/js/partial-page-load.js
  resource/js/tab-alpha.js
  tests/cypress/template/concept.cy.js
  tests/cypress/template/vocab-home.cy.js
Labels: bug
