Repository NatLibFi/Skosmos, pull requests merged in 2024-04, with the labels that each got.

#1620 Make LOC HTTP prefLabel header parsing case-insensitive (Skosmos 3)
  src/model/resolver/LOCResource.php
Labels: bug

#1621 Make LOC HTTP prefLabel header parsing case-insensitive (Skosmos 2)
  model/resolver/LOCResource.php
Labels: bug, Skosmos 2.X

#1615 Fixed accessibility issues reported by Cypress and added variables to Twig templates indicating the loaded template (issue1582)
  resource/js/tab-alpha.js
  resource/js/tab-hierarchy.js
  resource/js/vocab-search.js
  src/view/about.twig
  src/view/base-template.twig
  src/view/concept.twig
  src/view/error.twig
  src/view/feedback.twig
  src/view/landing.twig
  src/view/sidebar.inc
  src/view/vocab-home.twig
  src/view/vocab-search.twig
  tests/cypress/accessibility/axe-about.cy.js
  tests/cypress/accessibility/axe-concept.cy.js
  tests/cypress/accessibility/axe-vocab-home.cy.js
  tests/cypress/accessibility/axe-vocab.cy.js
Labels: bug, enhancement

#1614 Copy to clipboard button for notations
  resource/css/skosmos.css
  resource/js/copy-to-clipboard.js
  src/view/concept-card.inc
  tests/cypress/template/concept.cy.js
Labels: enhancement, classification

#1624 Add infinite scrolling to alphabetical index
  resource/css/skosmos.css
  resource/js/tab-alpha.js
  src/view/scripts.inc
Labels: enhancement

#1626 Sort concepts in hierarchical view by label and locale
  resource/js/tab-hierarchy.js
Labels: enhancement

#1628 Redesign initialization of Model and GlobalConfig to avoid chicken-and-egg situation
  src/entity.php
  src/index.php
  src/model/DataObject.php
  src/model/GlobalConfig.php
  src/model/Model.php
  src/model/Vocabulary.php
  src/model/VocabularyConfig.php
  src/rest.php
  tests/ConceptMappingPropertyValueTest.php
  tests/ConceptPropertyTest.php
  tests/ConceptPropertyValueLiteralTest.php
  tests/ConceptPropertyValueTest.php
  tests/ConceptSearchParametersTest.php
  tests/ConceptTest.php
  tests/DataObjectTest.php
  tests/FeedbackTest.php
  tests/GenericSparqlTest.php
  tests/GlobalConfigTest.php
  tests/Http304Test.php
  tests/JenaTextSparqlTest.php
  tests/ModelTest.php
  tests/PluginRegisterTest.php
  tests/RequestTest.php
  tests/ResolverTest.php
  tests/RestControllerTest.php
  tests/VocabularyCategoryTest.php
  tests/VocabularyConfigTest.php
  tests/VocabularyTest.php
  tests/WebControllerTest.php
  tests/cypress/e2e/fp-lang-yso-clang-result-vocab.cy.js
  tests/cypress/e2e/linked-data-entity.cy.js
  tests/jenatestconfig.ttl
Labels: bug

#1630 Fetch letters and concepts based on content language
  resource/js/tab-alpha.js
  tests/cypress/template/sidebar.cy.js
Labels: enhancement

#1632 Updated Norwegian (nn, nb) translations
  resource/translations/nb/LC_MESSAGES/skosmos.mo
  resource/translations/nn/LC_MESSAGES/skosmos.mo
  resource/translations/skosmos_nb.po
  resource/translations/skosmos_nn.po
Labels: translations
