Repository NatLibFi/Skosmos, pull requests merged in 2024-10, with the labels that each got.

#1680 Skosmos 2 Docker: upgrade to Ubuntu 22.04 base image and PHP 8.1
  dockerfiles/Dockerfile.ubuntu
Labels: bug, maintenance

#1682 Add PHP 8.3 support + change Docker base image to Ubuntu 24.04 with PHP 8.3
  .github/workflows/ci.yml
  composer.json
  dockerfiles/Dockerfile.ubuntu
  src/controller/EntityController.php
  src/controller/RestController.php
  src/controller/WebController.php
  src/model/BaseConfig.php
  src/model/Cache.php
  src/model/Concept.php
  src/model/ConceptProperty.php
  src/model/ConceptPropertyValue.php
  src/model/ConceptPropertyValueLiteral.php
  src/model/GlobalConfig.php
  src/model/LabelSkosXL.php
  src/model/Model.php
  src/model/PluginRegister.php
  src/model/Request.php
  src/model/Vocabulary.php
  src/model/VocabularyConfig.php
  src/model/resolver/LOCResource.php
  src/model/sparql/GenericSparql.php
  src/model/sparql/JenaTextSparql.php
Labels: maintenance

#1669 Css fixes of the landing page vocab list
  resource/css/skosmos.css
  src/view/landing.twig
Labels: front-end

#1688 Add cypress tests for alphabetical index Vue component
  tests/cypress/template/sidebar-alpha.cy.js
  tests/cypress/template/sidebar-hierarchy.cy.js
  tests/cypress/template/sidebar.cy.js
  tests/cypress/template/vocab-home.cy.js
  tests/test-vocab-data/test-551-A.ttl
  tests/testconfig.ttl
Labels: tests

#1695 Updated vocab load curl command to v8.5.0 compliant
  tests/init_containers.sh
Labels: bug, tests

#1689 Vocab search language menu
  resource/js/vocab-search.js
  src/view/scripts.inc.twig
  tests/cypress/template/vocab-search-bar.cy.js
Labels: front-end

#1702 Skosmos 2: Fix PHP 8.1 deprecation message that broke content language links
  model/Vocabulary.php
Labels: bug, Skosmos 2.X

#1697 Reimplement vocab home using Bootstrap Grid instead of tables
  resource/css/skosmos.css
  src/view/concept-card.inc.twig
  src/view/vocab-info.inc.twig
  tests/cypress/template/landing.cy.js
Labels: enhancement

#1698 Updates to php library dependencies
  composer.json
  tests/ConceptPropertyValueLiteralTest.php
  tests/ConceptTest.php
  tests/VocabularyConfigTest.php
Labels: maintenance

#1705 Don't HTML encode quotes in REST API callback, to fix ONKI Selector (Skosmos 2)
  controller/RestController.php
Labels: bug, REST, Skosmos 2.X
