Repository NatLibFi/Skosmos, pull requests merged in 2025-03, with the labels that each got.

#1757 Sub of 1712 translations of Aria tags in tab-hierarchy
  resource/js/tab-hierarchy.js
  resource/translations/messages.en.json
  resource/translations/messages.fi.json
  resource/translations/messages.sv.json
  tests/cypress/template/sidebar-hierarchy.cy.js
Labels: enhancement

#1766 Implement infinite scrolling in new and deprecated view
  resource/css/skosmos.css
  resource/js/tab-changes.js
  tests/cypress/template/sidebar-changes.cy.js
Labels: enhancement

#1774 Translations of Aria labels in vocab search Vue component
  resource/js/vocab-search.js
  resource/translations/messages.en.json
  resource/translations/messages.fi.json
  resource/translations/messages.sv.json
  tests/cypress/template/vocab-search-bar.cy.js
Labels: enhancement, translations

#1770 Add wrapper scripts for common translation operations
  .gitignore
  bin/extract-translations
  bin/pull-translations
  bin/push-translations
Labels: enhancement, translations

#1772 implement event listener for notifying when translations are ready
  resource/js/tab-alpha.js
  resource/js/tab-changes.js
  resource/js/tab-hierarchy.js
  resource/js/term-counts.js
  resource/js/translation-service.js
  resource/js/vocab-counts.js
  resource/js/vocab-search.js
Labels: enhancement, translations

#1777 Translations in groups view
  resource/js/tab-groups.js
  tests/cypress/template/sidebar-groups.cy.js
Labels: enhancement, translations

#1778 Upgrade to Jena Fuseki 5.3.0, including a new Dockerfile
  docker-compose.yml
  dockerfiles/jena-fuseki2-docker/Dockerfile
  dockerfiles/jena-fuseki2-docker/README.md
  resource/js/tab-hierarchy.js
  tests/cypress/template/sidebar-hierarchy.cy.js
Labels: maintenance

#1776 Translations of Aria labels in new and deprecated view
  resource/js/tab-changes.js
  tests/cypress/template/sidebar-changes.cy.js
Labels: enhancement, translations

#1780 Visual layout improvements especially for landing page
  resource/css/skosmos.css
  src/view/base-template.twig
  src/view/landing.twig
Labels: enhancement
