Repository NatLibFi/Skosmos, pull requests merged in 2025-05, with the labels that each got.

#1787 Narrower container for landing & other global page types
  resource/css/skosmos.css
Labels: enhancement

#1788 Upgrade to Fuseki 5.4.0 in Skosmos tests and containers
  docker-compose.yml
  tests/docker-compose.yml
Labels: maintenance

#1758 Global Search twig-template
  resource/css/skosmos.css
  src/controller/WebController.php
  src/view/global-search.twig
  src/view/search-results.inc.twig
  tests/cypress/template/global-search.cy.js
Labels: enhancement, front-end

#1791 Set max width for topbar and headerbar
  resource/css/skosmos.css
  src/view/base-template.twig
Labels: enhancement

#1790 New plugin infrastructure for Skosmos 3.0
  resource/js/make-plugin-callbacks.js
  resource/js/partial-page-load.js
  src/model/PluginRegister.php
  src/view/base-template.twig
  src/view/concept-card.inc.twig
  src/view/scripts.inc.twig
  src/view/vocab-info.inc.twig
  tests/PluginRegisterTest.php
  tests/cypress/template/plugins.cy.js
  tests/docker-compose.yml
  tests/plugins/test-plugin-vanilla-js/plugin.json
  tests/plugins/test-plugin-vanilla-js/stylesheet.css
  tests/plugins/test-plugin-vanilla-js/widget.js
  tests/plugins/test-plugin-vue/plugin.json
  tests/plugins/test-plugin-vue/stylesheet.css
  tests/plugins/test-plugin-vue/widget.js
  tests/testconfig.ttl
Labels: enhancement
