Repository NatLibFi/Skosmos, pull requests merged in 2025-01, with the labels that each got.

#1723 Add translations for tab-alpha.js and vocab-search.js (#1722)
  resource/js/tab-alpha.js
  resource/js/vocab-counts.js
  resource/js/vocab-search.js
  resource/translations/messages.en.json
  resource/translations/messages.fi.json
  resource/translations/messages.se.json
  resource/translations/messages.sv.json
  src/view/scripts.inc.twig
Labels: enhancement

#1742 [WIP] Responsive layout for the concept page
  resource/css/skosmos.css
  resource/js/concept-mappings.js
  src/view/concept-card.inc.twig
Labels: enhancement

#1750 Implementing new and deprecated view basic functionality using Vue
  resource/css/skosmos.css
  resource/js/tab-changes.js
  src/view/scripts.inc.twig
  tests/cypress/template/sidebar-changes.cy.js
  tests/testconfig.ttl
Labels: enhancement

#1741 Tab-alpha's Aria tag translations
  resource/js/tab-alpha.js
  resource/translations/messages.en.json
  resource/translations/messages.fi.json
  resource/translations/messages.sv.json
  tests/cypress/template/sidebar-alpha.cy.js
Labels: enhancement

#1754 Responsive layout for the vocabulary home page + layout adjustments
  resource/css/skosmos.css
  resource/js/concept-mappings.js
  src/view/base-template.twig
  src/view/concept-card.inc.twig
  src/view/vocab-info.inc.twig
  src/view/vocab-search.twig
Labels: enhancement

#1759 Fix scrollbar styling and visibility
  resource/css/skosmos.css
Labels: enhancement

#1762 Fixed dropdown menu width
  resource/js/vocab-search.js
Labels: bug, front-end

#1744 Truncate long search result lines
  resource/css/skosmos.css
  resource/js/truncate-search-results.js
  src/view/scripts.inc.twig
  tests/cypress/template/vocab-search.cy.js
Labels: enhancement, front-end
